CEO first commit
kuberMAPtes/practice-space pull request #4
Opened 2024-05-16 16:24 UTC by IwouldHelpYou

응 얼른 머지해

2024-05-16 16:25 UTC, IwouldHelpYou commented
왜 CEO 인데 머지 안되는거임

2024-05-16 16:26 UTC, IwouldHelpYou commented
![image](https://github.com/kuberMAPtes/practice-space/assets/123255935/d86ef8de-ca84-428d-be99-3f859b09f6c5)

2024-05-18 05:28 UTC, z-ral-dog commented
2nd commit : socket.IO 로 통신하는것 구현

2024-05-18 06:50 UTC, z-ral-dog commented
3rd commit : 닉네임 변경기능 구현

2024-05-18 06:54 UTC, rudeh1253 requested changes
gitignore 추가해 주세요 렉 걸려요

2024-05-18 06:56 UTC, closed without merging